export const CASE_GET_TABLE='CASE_GET_TABLE';
export const CASE_SET_SEARCHTERM='CASE_SET_SEARCHTERM';
export const CASE_SET_SEARCHPAGE='CASE_SET_SEARCHPAGE';
export const CASE_UPDATE='CASE_UPDATE';

export const CASETABLE_GET_TABLE='CASETABLE_GET_TABLE';
export const CASETABLE_SET_SEARCHTERM='CASETABLE_SET_SEARCHTERM';
export const CASETABLE_SET_SEARCHPAGE='CASETABLE_SET_SEARCHPAGE';
export const CASETABLE_SET_SEARCHID='CASETABLE_SET_SEARCHID';


export const TRACK_GET_TABLE='TRACK_GET_TABLE';
export const TRACK_SET_SEARCHTERM='TRACK_SET_SEARCHTERM';
export const TRACK_SET_SEARCHPAGE='TRACK_SET_SEARCHPAGE';
export const TRACK_UPDATE='TRACK_UPDATE';

export const TRACKRESULT_GET_TABLE= 'TRACKRESULT_GET_TABLE';
export const TRACKRESULT_SET_SEARCHTERM= 'TRACKRESULT_SET_SEARCHTERM';
export const TRACKRESULT_SET_SEARCHPAGE= 'TRACKRESULT_SET_SEARCHPAGE';
export const TRACKRESULT_SET_SEARCHID= 'TRACKRESULT_SET_SEARCHID';
export const TRACKRESULT_UPDATE='TRACKRESULT_UPDATE';
export const TRACKRESULT_GET_TIMEDATA='TRACKRESULT_GET_TIMEDATA';
export const TRACKRESULT_DEL_TIMEDATA='TRACKRESULT_DEL_TIMEDATA';

export const CHART_GET_TABLE='CHART_GET_TABLE';
export const CHART_SET_SEARCHTERM='CHART_SET_SEARCHTERM';


export  const MONITOR_GET_TABLE='MONITOR_GET_TABLE';
export  const MONITOR_UPDATE='MONITOR_UPDATE';

export const VIDEO_GET_TABLE='VIDEO_GET_TABLE';
export const VIDEO_SET_SEARCHTERM='VIDEO_SET_SEARCHTERM';
export const VIDEO_SET_SEARCHPAGE='VIDEO_SET_SEARCHPAGE';
export const VIDEO_UPDATE='VIDEO_UPDATE';

export const SYNTHESIS_GET_TABLE='SYNTHESIS_GET_TABLE';
export const SYNTHESIS_SET_SEARCHTERM='SYNTHESIS_SET_SEARCHTERM';
export const SYNTHESIS_SET_SEARCHPAGE='SYNTHESIS_SET_SEARCHPAGE';
export const SYNTHESIS_SET_SEARCHID='SYNTHESIS_SET_SEARCHID';
export const SYNTHESIS_SET_FLAG='SYNTHESIS_SET_FLAG';

export const USER_GET_LIST='USER_GET_LIST';
export const USER_SET_SEARCHTERM='USER_SET_SEARCHTERM';
export const USER_SET_SEARCHPAGE='USER_SET_SEARCHPAGE';
export const USER_GET_ONEADMIN='USER_GET_ONEADMIN';
export const USER_GET_ALLGROUP='USER_GET_ALLGROUP';
export const USER_LIST_UPDATE='USER_LIST_UPDATE';


export const ROLE_GET_GROUPLIST='ROLE_GET_GROUPLIST';
export const ROLE_SET_SEARCHTERM='ROLE_SET_SEARCHTERM';
export const ROLE_SET_SEARCHPAGE='ROLE_SET_SEARCHPAGE';
export const ROLE_UPDATE='ROLE_UPDATE';
export const ROLE_GET_ALLPRIVILEGE='ROLE_GET_ALLPRIVILEGE';
export const ROLE_PRIVILEGE_UPDATE='ROLE_PRIVILEGE_UPDATE';

export const REGISTER_GET_TABLE='REGISTER_GET_TABLE';
export const REGISTER_SET_SEARCHTERM='REGISTER_SET_SEARCHTERM';
export const REGISTER_SET_PAGETERM='REGISTER_SET_PAGETERM';
export const REGISTER_SET_SORTTERM='REGISTER_SET_SORTTERM';
export const REGISTER_GET_IDINFO='REGISTER_GET_IDINFO';
